[ColorScheme]
# Breeze Dark im qt5ct-Format (NICHT identisch zum KDE-.colors-Format!)
# Reihenfolge der 20 Farben:
#  WindowText, Button, Light, Midlight, Dark, Mid, Text, BrightText,
#  ButtonText, Base, Window, Shadow, Highlight, HighlightedText, Link,
#  LinkVisited, AlternateBase, NoRole, ToolTipBase, ToolTipText
# Letzter Wert (#80000000) ist optional Placeholder-Tinting fuer Qt 5.12+.
active_colors=#fffcfcfc, #ff31363b, #ff3b4045, #ff353a3f, #ff1d2023, #ff282c30, #fffcfcfc, #ffffffff, #fffcfcfc, #ff232629, #ff2a2e32, #ff14171a, #ff3daee9, #fffcfcfc, #ff1d99f3, #ff9b59b6, #ff2a2e32, #ff232629, #ff31363b, #fffcfcfc
disabled_colors=#ff7f8c8d, #ff31363b, #ff3b4045, #ff353a3f, #ff1d2023, #ff282c30, #ff7f8c8d, #ffffffff, #ff7f8c8d, #ff2a2e32, #ff31363b, #ff14171a, #ff3daee9, #fffcfcfc, #ff1d99f3, #ff9b59b6, #ff31363b, #ff232629, #ff31363b, #fffcfcfc
inactive_colors=#fffcfcfc, #ff31363b, #ff3b4045, #ff353a3f, #ff1d2023, #ff282c30, #fffcfcfc, #ffffffff, #fffcfcfc, #ff232629, #ff2a2e32, #ff14171a, #ff3daee9, #fffcfcfc, #ff1d99f3, #ff9b59b6, #ff2a2e32, #ff232629, #ff31363b, #fffcfcfc
